/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WithdrawRouteImport } from './routes/withdraw'
import { Route as GetUntiRouteImport } from './routes/get-unti'
import { Route as GetMizuhikiRouteImport } from './routes/get-mizuhiki'
import { Route as DepositRouteImport } from './routes/deposit'
import { Route as CounterRouteImport } from './routes/counter'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoStoreRouteImport } from './routes/demo.store'

const WithdrawRoute = WithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => rootRouteImport,
} as any)
const GetUntiRoute = GetUntiRouteImport.update({
  id: '/get-unti',
  path: '/get-unti',
  getParentRoute: () => rootRouteImport,
} as any)
const GetMizuhikiRoute = GetMizuhikiRouteImport.update({
  id: '/get-mizuhiki',
  path: '/get-mizuhiki',
  getParentRoute: () => rootRouteImport,
} as any)
const DepositRoute = DepositRouteImport.update({
  id: '/deposit',
  path: '/deposit',
  getParentRoute: () => rootRouteImport,
} as any)
const CounterRoute = CounterRouteImport.update({
  id: '/counter',
  path: '/counter',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStoreRoute = DemoStoreRouteImport.update({
  id: '/demo/store',
  path: '/demo/store',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/counter': typeof CounterRoute
  '/deposit': typeof DepositRoute
  '/get-mizuhiki': typeof GetMizuhikiRoute
  '/get-unti': typeof GetUntiRoute
  '/withdraw': typeof WithdrawRoute
  '/demo/store': typeof DemoStoreRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/counter': typeof CounterRoute
  '/deposit': typeof DepositRoute
  '/get-mizuhiki': typeof GetMizuhikiRoute
  '/get-unti': typeof GetUntiRoute
  '/withdraw': typeof WithdrawRoute
  '/demo/store': typeof DemoStoreRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/counter': typeof CounterRoute
  '/deposit': typeof DepositRoute
  '/get-mizuhiki': typeof GetMizuhikiRoute
  '/get-unti': typeof GetUntiRoute
  '/withdraw': typeof WithdrawRoute
  '/demo/store': typeof DemoStoreRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/counter'
    | '/deposit'
    | '/get-mizuhiki'
    | '/get-unti'
    | '/withdraw'
    | '/demo/store'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/counter'
    | '/deposit'
    | '/get-mizuhiki'
    | '/get-unti'
    | '/withdraw'
    | '/demo/store'
  id:
    | '__root__'
    | '/'
    | '/counter'
    | '/deposit'
    | '/get-mizuhiki'
    | '/get-unti'
    | '/withdraw'
    | '/demo/store'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CounterRoute: typeof CounterRoute
  DepositRoute: typeof DepositRoute
  GetMizuhikiRoute: typeof GetMizuhikiRoute
  GetUntiRoute: typeof GetUntiRoute
  WithdrawRoute: typeof WithdrawRoute
  DemoStoreRoute: typeof DemoStoreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/withdraw': {
      id: '/withdraw'
      path: '/withdraw'
      fullPath: '/withdraw'
      preLoaderRoute: typeof WithdrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-unti': {
      id: '/get-unti'
      path: '/get-unti'
      fullPath: '/get-unti'
      preLoaderRoute: typeof GetUntiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-mizuhiki': {
      id: '/get-mizuhiki'
      path: '/get-mizuhiki'
      fullPath: '/get-mizuhiki'
      preLoaderRoute: typeof GetMizuhikiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deposit': {
      id: '/deposit'
      path: '/deposit'
      fullPath: '/deposit'
      preLoaderRoute: typeof DepositRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/counter': {
      id: '/counter'
      path: '/counter'
      fullPath: '/counter'
      preLoaderRoute: typeof CounterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/store': {
      id: '/demo/store'
      path: '/demo/store'
      fullPath: '/demo/store'
      preLoaderRoute: typeof DemoStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CounterRoute: CounterRoute,
  DepositRoute: DepositRoute,
  GetMizuhikiRoute: GetMizuhikiRoute,
  GetUntiRoute: GetUntiRoute,
  WithdrawRoute: WithdrawRoute,
  DemoStoreRoute: DemoStoreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
